In [1]:
import requests
from bs4 import BeautifulSoup

In [42]:
BASE_URL = "https://www.mahindrafirstchoice.com/used-cars/bangalore"
headers = {
    "useragent": "Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/92.0.4515.107+Safari/537.36"
}

In [43]:
soup = BeautifulSoup(requests.get(BASE_URL,headers=headers).text,"html.parser")

In [81]:
cars_list = soup.select("#buyer_stock_results")[0]
rows = cars_list.select(".general-car")
result = []

for row in rows:
    info = row.select(".buyer_make")[0].text.split()
    year = info[0]
    brand = info[1]
    model = row.select(".buyer_variant")[0].text.strip()
    price = row.select(".car_price")[0].text
    buyer_location=row.select(".buyer_locations")[0].text
    specs = row.select(".spec-info-list")[0].select("li")
    km = specs[0].select(".overview_name")[0].text.replace(",","")
    type_of_car = specs[1].select(".overview_name")[0].text.strip()
    body_type = specs[2].select(".overview_name")[0].text
    owner = specs[3].select(".overview_name")[0].text
    
    data = {
        "year": year,
        "model": model,
        "model":model,
        "price":price,
        "buyer location":buyer_location,
        "kilometer":km,
        "type of car":type_of_car,
        "body type":body_type,
        "owner":owner
    }
    result.append(data)
    
result

[{'year': '2014',
  'model': 'Nano XT TWIST',
  'price': '1.6 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '9486 Kms',
  'type of car': 'Petrol',
  'body type': 'Hatchback',
  'owner': '1st Owner'},
 {'year': '2014',
  'model': 'Nano XT TWIST',
  'price': '1.75 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '55500 Kms',
  'type of car': 'Petrol',
  'body type': 'Hatchback',
  'owner': '2nd Owner'},
 {'year': '2007',
  'model': 'Wagon R VXI MINOR',
  'price': '1.9 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '67400 Kms',
  'type of car': 'Petrol',
  'body type': 'Hatchback',
  'owner': '3rd Owner'},
 {'year': '2007',
  'model': 'Wagon R LXI O',
  'price': '1.95 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '60600 Kms',
  'type of car': 'Petrol',
  'body type': 'Hatchback',
  'owner': '1st Owner'},
 {'year': '2009',
  'model': 'Zen Estilo VXI',
  'price': '2.25 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '51425 Kms',
  'type of car': 'Petrol',
  'body type': 'Hatchback',
  'owner': '1st Owner'},
 {'year': '2012',
  'model': 'Quanto C6',
  'price': '3.25 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '63925 Kms',
  'type of car': 'Diesel',
  'body type': 'SUV',
  'owner': '1st Owner'},
 {'year': '2016',
  'model': 'Kuv100(2016_2017) K2...',
  'price': '4.25 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '48713 Kms',
  'type of car': 'Petrol',
  'body type': 'SUV',
  'owner': '1st Owner'},
 {'year': '2008',
  'model': 'Innova 2.5 G1',
  'price': '5.3 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '2.37 Lakhs Kms',
  'type of car': 'Diesel',
  'body type': 'SUV',
  'owner': '1st Owner'},
 {'year': '2007',
  'model': 'Innova 2.5 V 7STR',
  'price': '6.65 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '75900 Kms',
  'type of car': 'Diesel',
  'body type': 'SUV',
  'owner': '2nd Owner'},
 {'year': '2014',
  'model': 'Duster 110 PS RXZ',
  'price': '6.95 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '1.23 Lakhs Kms',
  'type of car': 'Diesel',
  'body type': 'SUV',
  'owner': '1st Owner'},
 {'year': '2020',
  'model': 'Triber RXZ',
  'price': '7.45 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '12299 Kms',
  'type of car': 'Petrol',
  'body type': 'MPV',
  'owner': '1st Owner'},
 {'year': '2018',
  'model': 'Tiago XZ',
  'price': '5.75 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '29105 Kms',
  'type of car': 'Petrol',
  'body type': 'Hatchback',
  'owner': '1st Owner'},
 {'year': '2017',
  'model': 'Swift Dzire VXI',
  'price': '6.45 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '26724 Kms',
  'type of car': 'Petrol',
  'body type': 'Sedan',
  'owner': '1st Owner'},
 {'year': '2012',
  'model': 'Swift VDI',
  'price': '5.45 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '69928 Kms',
  'type of car': 'Diesel',
  'body type': 'Hatchback',
  'owner': '1st Owner'},
 {'year': '2017',
  'model': 'Jazz 1.2 S I VTEC',
  'price': '6.35 Lakhs',
  'buyer location': 'Bangalore',
  'kilometer': '27000 Kms',
  'type of car': 'Petrol',
  'body type': 'Hatchback',
  'owner': '1st Owner'}]

In [82]:
import csv

In [78]:
fields=['year','make','model','price','buyer location','kilometer','type of car','body type','owner']
filename="car_record_banglore.csv"

with open(filename,'w') as csvfile:
    writer=csv.DictWriter(csvfile,fieldnames=fields)
    writer.writeheader()
    writer.writerows(result)

In [79]:
import pandas as pd

In [80]:
df=pd.read_csv("car_record_banglore.csv")
df

,year,make,model,price,buyer location,kilometer,type of car,body type,owner
0,2014,NaN,Nano XT TWIST,1.6 Lakhs,Bangalore,9486 Kms,Petrol,Hatchback,1st Owner
1,2014,NaN,Nano XT TWIST,1.75 Lakhs,Bangalore,55500 Kms,Petrol,Hatchback,2nd Owner
2,2007,NaN,Wagon R VXI MINOR,1.9 Lakhs,Bangalore,67400 Kms,Petrol,Hatchback,3rd Owner
3,2007,NaN,Wagon R LXI O,1.95 Lakhs,Bangalore,60600 Kms,Petrol,Hatchback,1st Owner
4,2009,NaN,Zen Estilo VXI,2.25 Lakhs,Bangalore,51425 Kms,Petrol,Hatchback,1st Owner
5,2012,NaN,Quanto C6,3.25 Lakhs,Bangalore,63925 Kms,Diesel,SUV,1st Owner
6,2016,NaN,Kuv100(2016_2017) K2...,4.25 Lakhs,Bangalore,48713 Kms,Petrol,SUV,1st Owner
7,2008,NaN,Innova 2.5 G1,5.3 Lakhs,Bangalore,2.37 Lakhs Kms,Diesel,SUV,1st Owner
8,2007,NaN,Innova 2.5 V 7STR,6.65 Lakhs,Bangalore,75900 Kms,Diesel,SUV,2nd Owner
9,2014,NaN,Duster 110 PS RXZ,6.95 Lakhs,Bangalore,1.23 Lakhs Kms,Diesel,SUV,1st Owner
10,2020,NaN,Triber RXZ,7.45 Lakhs,Bangalore,12299 Kms,Petrol,MPV,1st Owner
11,2018,NaN,Tiago XZ,5.75 Lakhs,Bangalore,29105 Kms,Petrol,Hatchback,1st Owner
12,2017,NaN,Swift Dzire VXI,6.45 Lakhs,Bangalore,26724 Kms,Petrol,Sedan,1st Owner
13,2012,NaN,Swift VDI,5.45 Lakhs,Bangalore,69928 Kms,Diesel,Hatchback,1st Owner
14,2017,NaN,Jazz 1.2 S I VTEC,6.35 Lakhs,Bangalore,27000 Kms,Petrol,Hatchback,1st Owner